version: 2
updates:
  # Maintain dependencies for the Java ecosystem using Gradle or Maven
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"
    rebase-strategy: "auto"
    reviewers:
      - "reviewer1"
      - "reviewer2"
    labels:
      - "dependencies"
      - "java"
    ignore:
      - dependency-name: "com.example.unwanted"
        versions: ["1.x", "< 2.0.0"]

  # Optionally maintain dependencies for the GitHub Actions workflow
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"
    rebase-strategy: "auto"
    reviewers:
      - "bishopwalker"
      - "reviewer2"
    labels:
      - "dependencies"
      - "actions"
    ignore:
      - dependency-name: "actions/checkout"
        versions: ["2.x"]

  #